### ISSUE TITLE
USER STORY <shopping>

### ISSUE THREAD

**Issue by Mi-Py-1** [Mi-Py-1/Love-Running-Does-Mike#12]
As a **customer** I can **see recommended products** so that **I can shop with trust**.

**Acceptance Criteria:**

- [ ]  List of recommended products or list of for sale products.
- [ ]  Shopping facility that is clear, safe. 
- [ ] Clear timescales and rpicing shown. 

**Tasks:**
- [ ] Create shopping framework using html.
- [ ] Link images using CSS.
- [ ]  Create shopping functionality and cart using javascript.
- [ ]  Ensure secruty of shopping process.
